### ISSUE TITLE
Cannot style 2nd level labels

### ISSUE THREAD

**Issue by kamilkulig** [blacklabel/grouped_categories#117]
**Example:** https://jsfiddle.net/kkulig/jjqjrsgv/

**Expected behavior:**
0-level label should be green. 2nd level labels should be pink.

**Actual behavior:**
0-level label is pink. It seems that both `labels.groupedOptions[1].style` and `labels.style` are used to style the same level: 0. Last code snippet on this page: https://www.highcharts.com/plugin-registry/single/11/Grouped-Categories says that `labels.groupedOptions[1].style` should be used to style the 2nd level.

**Comment by KacperMadej** [comment]
Hi,

In styled mode (and your are using Highcharts in styled mode) labels style should be set through CSS.
Demo: https://jsfiddle.net/jjqjrsgv/1/

**Comment by DirkDeWachter** [comment]
Moreover, you can add this to groupedOptions:
	    groupedOptions: [{ "class": "**level1**"} ]

and then use this class add CSS:
	    .highcharts-axis-labels.highcharts-xaxis-labels text.**level1**,
	    .highcharts-axis-labels.highcharts-xaxis-labels text.**level1** tspan { fill: red !important }

I've added both text.**level1** and text.**level1** tspan, as sometimes the label is wrapped in a <tspan>-element. I've also added "!important" as the SVG <text> element seems to get an automatic inline style, which would override the CSS. 

Dirk

**Comment by adong** [comment]
@DirkDeWachter Why uses `class` instead of `className`? I'm thinking you are leveraging code in here, are you? Thanks.

https://github.com/blacklabel/grouped_categories/blob/f93ad04c668a0d7e5443d97358dca77bd31cf8b8/grouped-categories.js#L189

**Comment by DirkDeWachter** [comment]
Hi,

There seems to be some misunderstanding.
I mentioned in my thread to add class to labels.groupedOptions. For xAxis, the option className is of course well suited.

One needs “class” in labels.groupedOptions and not className, as for labels.groupedOptions “className” is not translated to “class”.
The difference – in your fiddle – would be in the resulting svg-code for “level1”:
With className in groupedOptions:  <text x="160" text-anchor="middle" y="299.8988923297811" className="level1" transform="translate(0,0)" visibility="visible">Fruit</text>
With class in groupedOptionsc: <text x="160" text-anchor="middle" y="299.8988923297811" class="level1" transform="translate(0,0)" visibility="visible">Fruit</text>

Only with “class” the labels.groupedOptions  part “style: { color: red }” for level1 can be replaced by an equivalent CSS:
.highcharts-axis-labels.highcharts-xaxis-labels text.level1 {  fill: red; }

I hope this better explains my comment.

Dirk


Van: Alan Dong <notifications@github.com>
Verzonden: donderdag 6 september 2018 23:08
Aan: blacklabel/grouped_categories <grouped_categories@noreply.github.com>
CC: De Wachter, Dirk <dirk.dewachter@zorg-en-gezondheid.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [blacklabel/grouped_categories] Cannot style 2nd level labels (#117)


@DirkDeWachter<https://github.com/DirkDeWachter> Why uses class instead of className? I'm thinking you are leveraging code in here, are you? Thanks.

https://github.com/blacklabel/grouped_categories/blob/f93ad04c668a0d7e5443d97358dca77bd31cf8b8/grouped-categories.js#L189
