### ISSUE TITLE
Reversed category for tooltip

### ISSUE THREAD

**Issue by yohannbalawender** [blacklabel/grouped_categories#51]
Hey,

First at all, thanks for this plugin, very usefull to display several dimensions.

However, I'd like to know if there is a way to reverse category for tooltip:
In the case of your example, I'd like to display " Fruit, Apple " instead of " Apple, Fruit ".

Or, if there is not, could you implement this feature ?

Thank you.

**Comment by pawelfus** [comment]
Sure, simply use `tooltip.headerFormat` as always:

        tooltip: {
            headerFormat: '{point.key.parent.name}, {point.key.name} <br>'
        },

Demo: http://jsfiddle.net/TFhd7/185/

**Comment by yohannbalawender** [comment]
Awww it was as simple as that ?

Thanks anyway.

**Comment by pawelfus** [comment]
As you can see. :)

**Comment by yohannbalawender** [comment]
New issue anyway: I've got more than 2 levels of 'grouped categories', so the first is still not displayed.

Related to your example, I would like to have " Fruit, Apple, Granny Smith ", and I've actually got " Apple, Granny Smith ".

**Comment by pawelfus** [comment]
In that case use `{point.key.parent.parent.name}` If you have more categories, use several times `parent` - each time you go one level deeper. Of course, that solution works only when you have always the same number of levels. 

Otherwise use `tooltip.formatter` and in that formatter you have access to categories using `this.key`.
